# Generated by Django 4.2.20 on 2025-04-20 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WishListElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a name for your wish', max_length=100)),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, help_text='Enter optional notes', max_length=1000, null=True)),
                ('link', models.URLField(help_text='Link(s) to buy your product')),
                ('status', models.BooleanField(default=False, help_text='Have you realize your wish?')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['status', '-date'],
            },
        ),
    ]
