# Generated by Django 4.2.20 on 2025-04-20 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_wishlistelement_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlistelement',
            name='list',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlist.wishlist'),
        ),
    ]
