# Generated by Django 4.2.20 on 2025-04-20 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_wishlistelement_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistelement',
            name='link',
            field=models.URLField(help_text='Link(s) to buy your product', null=True),
        ),
    ]
