# Generated by Django 4.2.20 on 2025-04-20 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0004_alter_wishlistelement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistelement',
            name='link',
            field=models.URLField(blank=True, help_text='Link(s) to buy your product', null=True),
        ),
    ]
