# Generated by Django 4.2.20 on 2025-04-21 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0005_alter_wishlistelement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlistelement',
            name='status',
            field=models.BooleanField(default=False, help_text='Have you realized your wish?'),
        ),
    ]
