# Generated by Django 4.2.20 on 2025-04-21 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_alter_wishlistelement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, help_text='A brief description of your wishlist', max_length=300, null=True),
        ),
    ]
