# Generated by Django 4.2.20 on 2025-04-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0008_alter_wishlist_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='description',
            field=models.TextField(blank=True, default=' ', help_text='A brief description of your wishlist', max_length=300, null=True),
        ),
    ]
